### ISSUE TITLE
Update upgrade-test-harness to work with k8s v0.26.1

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6442]
Since

- https://github.com/elastic/cloud-on-k8s/pull/6340

`hack/upgrade-test-harness` no longer compiles:
```sh
> go run main.go
# github.com/elastic/cloud-on-k8s/v2/hack/upgrade-test-harness/k8s
k8s/kubectl.go:120:40: not enough arguments in call to h.factory.Validator
        have (bool)
        want (string, *"k8s.io/cli-runtime/pkg/resource".QueryParamVerifier)
```

The new signature is `Validator(validationDirective string, verifier *resource.QueryParamVerifier)`.

What is a verifier? In `v0.27.0-alpha.2`, the verifier is created inside `Validator` ([code](https://github.com/kubernetes/kubectl/commit/e5c05deb7b6392eb0cb8df127c998b6d9e1ad8bf#diff-104467bd448e771489466096199d20813345b369308a9be3b4c23511adeeae94)):

```go
dynamicClient, err := f.DynamicClient()
if err != nil {
  return nil, err
}
// Create the FieldValidationVerifier for use in the ParamVerifyingSchema.
verifier := resource.NewQueryParamVerifier(dynamicClient, f.OpenAPIGetter(), resource.QueryParamFieldValidation)
```

**Comment by thbkrkr** [comment]
`testdata/upcoming` shouldn't have been deleted in #6326.
