### PR TITLE
Fix upgrade test harness

### LINKED ISSUE #6442: Update upgrade-test-harness to work with k8s v0.26.1
Since

- https://github.com/elastic/cloud-on-k8s/pull/6340

`hack/upgrade-test-harness` no longer compiles:
```sh
> go run main.go
# github.com/elastic/cloud-on-k8s/v2/hack/upgrade-test-harness/k8s
k8s/kubectl.go:120:40: not enough arguments in call to h.factory.Validator
        have (bool)
        want (string, *"k8s.io/cli-runtime/pkg/resource".QueryParamVerifier)
```

The new signature is `Validator(validationDirective string, verifier *resource.QueryParamVerifier)`.

What is a verifier? In `v0.27.0-alpha.2`, the verifier is created inside `Validator` ([code](https://github.com/kubernetes/kubectl/commit/e5c05deb7b6392eb0cb8df127c998b6d9e1ad8bf#diff-104467bd448e771489466096199d20813345b369308a9be3b4c23511adeeae94)):

```go
dynamicClient, err := f.DynamicClient()
if err != nil {
  return nil, err
}
// Create the FieldValidationVerifier for use in the ParamVerifyingSchema.
verifier := resource.NewQueryParamVerifier(dynamicClient, f.OpenAPIGetter(), resource.QueryParamFieldValidation)
```

### PR DESCRIPTION
**Pull request by thbkrkr**
- Remove old `v160` that doesn't work on new k8s version because CRDs use `apiextensions.k8s.io/v1beta1`

- Update stack version to `8.6.1` for eck `v261`

- Resurrect testdata/upcoming/stack.yml mistakenly deleted in #6326

- ~Refactoring `h.factory.Validator` that doesn't compile since #6340~ (I mistakenly thought k8s.io dependencies had been upgraded.)

Resolves #6442.

### CODE REVIEW

File: hack/upgrade-test-harness/k8s/kubectl.go [hunk 1]
```diff
@@ -117,7 +117,12 @@ func (h *Kubectl) GetPods(namespace string, labelSelector string) ([]corev1.Pod,
 
 // LoadResources loads manifests from the given file path.
 func (h *Kubectl) LoadResources(filePath string) (*resource.Result, error) {
-	validator, err := h.factory.Validator(true)
+	dynamicClient, err := h.factory.DynamicClient()
+	if err != nil {
+		return nil, err
+	}
+	verifier := resource.NewQueryParamVerifier(dynamicClient, h.factory.OpenAPIGetter(), resource.QueryParamFieldValidation)
+	validator, err := h.factory.Validator(metav1.FieldValidationStrict, verifier)
```
Comment (pebrc) [inline hack/upgrade-test-harness/k8s/kubectl.go:125]: Did you forget to commit `go.mod` because this PR still has
```go.mod
require (
	k8s.io/api v0.22.4
	k8s.io/apimachinery v0.22.4
	k8s.io/cli-runtime v0.22.4
	k8s.io/client-go v0.22.4
	k8s.io/kubectl v0.22.4
)
```

**Review by pebrc — APPROVED** [review]
